### ISSUE TITLE
How to Add Inst_ID as a University ID in a profile 

### ISSUE THREAD

**Issue by AbdulQadeerKhan7886** [ExLibrisGroup/alma-csv-user-load#101]
![image](https://github.com/user-attachments/assets/157b982b-068a-4c2a-b126-b09a7000443f)
![image](https://github.com/user-attachments/assets/3d4a5465-0358-4c25-8f40-2d42b9f34c2d)
![image](https://github.com/user-attachments/assets/7628d9f8-8f67-4c2c-b177-7a6879401057)

It is working as a barcode but i want to add it as a University ID.

Thankyou.

**Comment by AbdulQadeerKhan7886** [comment]
![image (3)](https://github.com/user-attachments/assets/05245bdb-5d0d-48ef-be93-1b29f0a5016b)
![image (2)](https://github.com/user-attachments/assets/0f7d2b64-ce48-4bba-9390-c260490384d3)
![image (1)](https://github.com/user-attachments/assets/f9db4ce5-5e94-4030-b1e1-1fc4b5bafb8d)

**Comment by mgobat** [comment]
@AbdulQadeerKhan7886, do you get any messages on the "Results" display after clicking "Load user" button and confirming the add/update? Is "University ID" the identifier type code or the identifier type description?

I haven't been able to replicate the problem yet. Thanks.

**Comment by AbdulQadeerKhan7886** [comment]
@mgobat Thanks for getting back. 
University ID is appearing as Identifier type in Alma. 
But I've seen INST_ID in csv manual file but it is not mapping.

**Comment by AbdulQadeerKhan7886** [comment]
![inst](https://github.com/user-attachments/assets/23e57e6b-c5de-4ac0-96ae-cb87a99acfce)

**Comment by AbdulQadeerKhan7886** [comment]
with INST_ID it gives this error and same with University ID
![inst](https://github.com/user-attachments/assets/a13951a8-8a0c-4111-a1ac-f841e08741aa)

**Comment by AbdulQadeerKhan7886** [comment]
![image](https://github.com/user-attachments/assets/9ada25bc-fcd2-4805-bad3-050a8d0ccadf)
![image](https://github.com/user-attachments/assets/260d7809-96d2-4c0d-8a5a-c4c63893fca7)

issue :(

**Comment by mgobat** [comment]
@AbdulQadeerKhan7886, ok, it looks like we just need to learn what the identifier type code is for "University ID". Do you have an Alma General Administrator who may be able to help get that?

**Comment by mgobat** [comment]
@AbdulQadeerKhan7886, you can see the user identifier types in Alma at Admin -> User Management -> User Identifier Types. You need to use the value in the CODE column when using the CSV User Load Cloud App. Looks like you might be looking for "UNIV_ID".

**Comment by AbdulQadeerKhan7886** [comment]
![image](https://github.com/user-attachments/assets/1170267e-3632-4772-9d08-99174ebdcf20)

@mgobat , 
UNIV_ID and INST_ID is not showing any result. :(

**Comment by AbdulQadeerKhan7886** [comment]
![image](https://github.com/user-attachments/assets/2d26805b-6db8-487e-b9d8-7ac72f681269)

I can't see specifically "User Identifier types" tab.

**Comment by AbdulQadeerKhan7886** [comment]
![image](https://github.com/user-attachments/assets/003d0c4b-0218-4144-b57d-e55d120977bd)
![image](https://github.com/user-attachments/assets/cecb819d-18ac-4264-8c37-6729b71c8b79)
Try above,  and got this error below. 👎 

![image](https://github.com/user-attachments/assets/da6f997b-c465-4d41-b7bc-adaa3ddef073)

please have a look, @mgobat

**Comment by mgobat** [comment]
@AbdulQadeerKhan7886, I'm sorry this isn't working for you yet. Could you please export your import profile and post it here? I want to be sure I'm using the exact same options. To export the profile:

- Open the "CSV User Load" Cloud App
- Click the "..." icon in the title bar
- Click the "gear" icon
- Select the profile you are using
- Click "Share"
- Click "Export current profile"

The profile will be saved in your "Downloads" folder with the profile name + .json as the file name.

Also, a sample input file would help. Please scrub the sample file of any personal identifying information before posting it.

Thanks.

**Comment by AbdulQadeerKhan7886** [comment]
Yes sure, @mgobat 
here you go. 
[UID_testing_3.xlsx.csv](https://github.com/user-attachments/files/16418292/UID_testing_3.xlsx.csv)
[UID_Test_uniid.json](https://github.com/user-attachments/files/16418294/UID_Test_uniid.json)

**Comment by mgobat** [comment]
Thanks, @AbdulQadeerKhan7886. I have replicated the problem. Looking into it....

**Comment by mgobat** [comment]
@AbdulQadeerKhan7886 , the date format in your input file is the first problem. Please change it as follows:
Date fields (e.g. birth date and expiration date) must be in the yyyy-mm-dd format.

Give that a try. Thanks.

**Comment by AbdulQadeerKhan7886** [comment]
Done , Thanks a lot. @mgobat
