### ISSUE TITLE
CSV format

### ISSUE THREAD

**Issue by stopete** [ExLibrisGroup/alma-csv-user-load#14]
what is the csv format, can I get an example? Appreciate your help.

**Comment by jweisman** [comment]
Hi. Have you seen the on line help? It includes examples of various CSV files and a list of supported fields:
https://github.com/jweisman/alma-csv-user-load/wiki/Alma-CSV-User-Load-Manual

**Comment by jweisman** [comment]
Feel free to reopen if there are still questions.
