### ISSUE TITLE
Additional field

### ISSUE THREAD

**Issue by billto-lib** [ExLibrisGroup/alma-csv-user-load#16]
Hi,

Thanks a lot for the cloud app and it really help us as we've lots of internal accounts to create and update. For comprehensive updates, is it possible to add some fields which Admin job also not support? For example, the "Job Category" field is not available for batch update in Admin job. If it's possible, it do great help to us.

Thanks again.

Bill

**Comment by jweisman** [comment]
Hi @billto-lib . Glad you find the app useful. We've added the additional field (via 8271fd7). Check out the updated [documentation](https://github.com/ExLibrisGroup/alma-csv-user-load/wiki/Alma-CSV-User-Load-Manual#supported-fields). Let us know how that works for you.
