### ISSUE TITLE
Text on app components are not showing well in CN UI

### ISSUE THREAD

**Issue by ling-jiang-exl** [ExLibrisGroup/alma-csv-user-load#17]
When the Alma is chosen to use CN, the text on the application components, such as buttons and dropdown lists, are not showing at all.

**Comment by jweisman** [comment]
Thanks for reporting this! It should be fixed now.

![Screen Shot 2020-12-31 at 15 57 23 ](https://user-images.githubusercontent.com/80420/103415543-3532ef80-4b8b-11eb-944b-3dea789a0e62.png)
