### ISSUE TITLE
additional field - proxy_for_user

### ISSUE THREAD

**Issue by yirankim** [ExLibrisGroup/alma-csv-user-load#18]
Hi,

Thank you so much for this useful app. 
Can we have an additional field 'proxy_for_user(s)'? 
It would save a lot of time for us. 

Regards,
Yi Ran

**Comment by jweisman** [comment]
Thanks for your suggestion. We will try to add this field.

**Comment by jweisman** [comment]
Hi @yirankim - we looked into this and it appears the updating proxy for users is not yet supported by the API. We are looking in to see if this is possible to add in the near future.

**Comment by jweisman** [comment]
Quick update on this issue- the field was added to the underlying API in the August Alma release. We'll work on adding it to the app when the August release is on the sandbox.

**Comment by jweisman** [comment]
Unfortunately we ran into an issue with this change. Hopefully it will be in the next release or two. Sorry for the inconvenience.

**Comment by jweisman** [comment]
This was finally completed- thanks for your patience. App [updated](https://github.com/ExLibrisGroup/alma-csv-user-load/releases/tag/1.6.0) for the sandbox. Will work with production Alma in two weeks with the October release.
