### ISSUE TITLE
Ability to set templates institution wide or share templates between users

### ISSUE THREAD

**Issue by msrachellouise** [ExLibrisGroup/alma-csv-user-load#19]
To save time, we would like to be able to set templates institution wide, rather than each user have to set their own templates

**Comment by jweisman** [comment]
Thanks for your suggestion. We will look into see if this is possible to implement.

**Comment by seanpurcell** [comment]
Agreed that being able to set templates institution-wide would a be great addition.  At the NZ level would be _even better_! 

Perhaps a lower hanging fruit might be to simply add the ability to export CSV profiles.  This would allow for sharing the profile with other users so they could easily import/add it.  We're hoping to use this for our 26 institution consortia to load their faculty and staff (student imports are already automated), and it's a bit of a harder sell if they each have to set up the CSV profile.   :)

Thanks for implementing this @jweisman!

**Comment by jweisman** [comment]
An update on this issue- we have implemented the option to share profiles. It's waiting for the ability to download files from a Cloud App, which is available in the Alma June release. So here's a preview and we'll update next month.


https://user-images.githubusercontent.com/80420/115175925-ac59a880-a0d4-11eb-9aad-7a889dffeb54.mov

**Comment by seanpurcell** [comment]
Thanks @jweisman!  This will be very helpful.

**Comment by jweisman** [comment]
This feature was [released](https://github.com/ExLibrisGroup/alma-csv-user-load/releases/tag/v1.3.0). Note that this features works best with the Alma June 2021 release, available currently on sandbox instances and on 7 June in production instances.

Thanks for your feedback. Feel free to comment here if you have any questions.
