### ISSUE TITLE
2 or more Identifier Type

### ISSUE THREAD

**Issue by ian-hey** [ExLibrisGroup/alma-csv-user-load#21]
Great app when our SIS went down

would be great if you could loud more than 1 Identifier Type

**Comment by jweisman** [comment]
Thanks for your comment. This should be available.

Using this profile:
![Screen Shot 2021-03-24 at 8 41 53 ](https://user-images.githubusercontent.com/80420/112266549-d6a67a80-8c7c-11eb-95a7-d9687e4d8b99.png)

And this sample file:
```
First Name,Last Name,Email,Email Type,Identifer Type 1,Identifier 1,Identifier Type 2,Identifier 2
Josh,Testman,josh@testman.com,school,BARCODE,432432432,INST_ID,josh.testman
Harold,Henry,harold@henry.com,school,BARCODE,789002,INST_ID,harold.henry
Jeff,Stern,jeff.stern@gmail.com,school,BARCODE,312312321,INST_ID,jeff.stern
Hank,Peterson,hank.peterson@gmail.com,school,BARCODE,4352423432,INST_ID,hank.peterson
Frank,Abignale,hank.peterson@gmail.com,school,BARCODE,12312312312,INST_ID,frank.abingale
```

We get these results:
![Screen Shot 2021-03-24 at 8 41 18 ](https://user-images.githubusercontent.com/80420/112283737-2131f200-8c91-11eb-84cb-964c955f89fa.png)

Let us know how that works for you.

**Comment by ian-hey** [comment]
All fixed thanks josh
