### ISSUE TITLE
Buttons are not displayed in Spanish language

### ISSUE THREAD

**Issue by malvaraa** [ExLibrisGroup/alma-csv-user-load#24]
Hi,

We are using the app, is very useful!!, with english language all is perfect, but if we use Alma in the spanish version some buttons are not activated. Attached a file with the example.
Regards,
Maribel
![csvuserloader](https://user-images.githubusercontent.com/82615239/114938843-98c8ec00-9e0d-11eb-9dca-c4c4ed01a314.JPG)

**Comment by jweisman** [comment]
Thanks for this report. We released a small version which fixes this issue. And we'd be happy to receive any fixes to the Spanish translations as well : )
