### ISSUE TITLE
User Group - Failed: Given user group is not legal.

### ISSUE THREAD

**Issue by ling-jiang-exl** [ExLibrisGroup/alma-csv-user-load#29]
Hi Team,

When I import with the following file:
first_name,last_name,primary_identifier,email_types,email_address,password,user_group
exl,test202103,exltest202103,work,exl_test202103@exl.com,Abcd1234!,Staff
The app complains that: Given user group is not legal.

However, "Staff" is exactly the user group used in Alma.
If I use "staff" instead, Alma will create a new user group "staff (not listed)".
I think this might be an bug, please fix it.

Thank you.

Ling

**Comment by jweisman** [comment]
Hi @ling-jiang-exl . The easiest way to check the allowed email types is to log into the Developer Network with an account attached to the institution, and then check the [listed email types](https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_user.xsd/?tags=POST#email_types):
<img width="893" alt="Screen Shot 2021-05-16 at 6 45 29 " src="https://user-images.githubusercontent.com/80420/118384844-55cb8580-b612-11eb-9cbf-b1404147b7b8.png">

Is that possible?

**Comment by ling-jiang-exl** [comment]
Hi @jweisman, thanks for your reply. However, the issue here is not about the Email Type but the User Group field. When using "Staff" the app complains it is illegal, when use "staff" the app creates a new "staff (not listed)" user group. Please advise, thank you.

**Comment by jweisman** [comment]
Hi @ling-jiang-exl - sorry about that misunderstanding. The user groups are also listed on the [same page](https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_user.xsd/?tags=POST). Looks like the default values include STAFF. Does that work for you?

![Screen Shot 2021-05-18 at 18 58 12 ](https://user-images.githubusercontent.com/80420/118684638-0f8d4680-b80b-11eb-92aa-94a79063db20.png)

**Comment by jweisman** [comment]
Closing for now- feel free to open if the question remains.
