### ISSUE TITLE
Is it possible to delete fields?

### ISSUE THREAD

**Issue by jdonaghe** [ExLibrisGroup/alma-csv-user-load#30]
For example, we'd like to delete home address information from a user record. When 'Address Line 1' is empty in the CSV file you get an error message 'Failed: Mandatory field is missing: address line1'

**Comment by jweisman** [comment]
Hi @jdonaghe - thanks for your question. Currently deleting repeatable fields such as addresses is not possible. Is this a common use case where you'd need to delete addresses in bulk via CSV?

**Comment by jdonaghe** [comment]
Thanks for answering @jweisman. The use case is more of a one-off scenario, where I have a specific set of users who are no longer being updated by the student integration profile and I'm trying to find the most efficient/simple way of removing address information from their records.

**Comment by jweisman** [comment]
Understood @jdonaghe - unfortunately this may not be the best way to accomplish that. Sorry.
