### ISSUE TITLE
Would be great to be able to download the event log rather than viewing it on screen.

### ISSUE THREAD

**Issue by seanpurcell** [ExLibrisGroup/alma-csv-user-load#33]
We're going to be using this cloud app exclusively in "Add" mode, rather than "Add/Update", due to the fact that in our case Alma may have more patron data fields populated than the source of the CSV (so lots of data gets lost for existing patrons).   So when we run an import, MOST of the patrons in the CSV are already be in Alma, which results in an error/warning appearing on the screen for each of these patrons after the load.  It would be great to be able to suppress the error list and instead offer up a link to download the error report for later review, and then simply show stats of the import on the screen (x number of patrons ignored, x number of patrons loaded, etc).  As for the on screen error/warning report, we can simply do a "select all" and save it to a text file, but it would be much more convenient to download it via a link.  Thanks for all your work on this @jweisman!

**Comment by jweisman** [comment]
Thanks for the suggestion @seanpurcell . Makes sense to provide the ability to show a summary and to hide and download the log. 

Regarding the Add/Update, I'm curious if you've tried it as it is supposed to merge the records at some level. Of course we can't duplicate all of the complexity of the SIS merge, but it may still be useful for you.

**Comment by seanpurcell** [comment]
Hi @jweisman,

We've definitely tried it in update mode in one of our sandboxes, and based on our testing, it replaces the data in Alma with the data from the csv.  I'm tempted to go back and try this again, but at the time, this was our conclusion.  For instance, for a given user, if there's a phone number in the csv, and there are two phone numbers in Alma for that user, after the load, the only phone number in Alma is the one from the CSV.  

From what I've read in the sis documentation, the patron sync operates in "Swap All" mode, so if there's a match, it imports the new data and clears out the old data.  For example, search for "swap all":
https://developers.exlibrisgroup.com/alma/integrations/user-management/sis/synch/

I could of course be overlooking something, and I'd be glad to be proven wrong on this!

thanks again,
Sean

**Comment by jweisman** [comment]
Hi @seanpurcell - you're right about phone numbers as they are all swapped out. Same for addresses, email addresses, etc. Other (single) fields, like job type, user group, etc. would be merged with the incoming record, but it appears that doesn't help in your case.

**Comment by jweisman** [comment]
Hi @seanpurcell - we just [released](https://github.com/ExLibrisGroup/alma-csv-user-load/releases/tag/v1.4.0) a new version which includes the ability to hide the log. Let us know how it works for you.

**Comment by seanpurcell** [comment]
Thanks @jweisman! We'll check it out asap!

**Comment by jweisman** [comment]
Closing this for now after the addition of the log. Let us know if there are any other comments.
