### ISSUE TITLE
Enhancement request - Add title field

### ISSUE THREAD

**Issue by mck1777** [ExLibrisGroup/alma-csv-user-load#36]
Any chance of getting title (from the UserTitle table code) added as a supported field. We are a military library and I would like to be able to upload their rank at same time I upload the new class list.
![image](https://user-images.githubusercontent.com/72558867/123660549-c2d15e00-d801-11eb-8a43-aecdbc8d924c.png)

Thanks for considering this.

maryclare koenig

**Comment by jweisman** [comment]
Hi @mck1777 . We added this field in the [latest release](https://github.com/ExLibrisGroup/alma-csv-user-load/releases/tag/v1.4.2). Be sure to use the code from the table. Let us know how it goes.
