### ISSUE TITLE
Error message when adding note type

### ISSUE THREAD

**Issue by mck1777** [ExLibrisGroup/alma-csv-user-load#37]
I am getting the following error
Failed: The parameter note_type  is invalid. Received: REGISTRAR. 

Documentation lists it as a note type
Note type

    OTHER (viewable in Discovery), LIBRARY, ADDRESS, BARCODE, CIRCULATION, ERP, POPUP (General), REGISTRAR

Any suggestions?
maryclare koenig

**Comment by jweisman** [comment]
Hi @mck1777 . Unfortunately the code for the Registrar note is `REGISTAR`. I updated the doc. Let us know if that doesn't work for you.

**Comment by mck1777** [comment]
too funny. awesome that works. now to load next student group.

Thanks for the fix

maryclare
