### ISSUE TITLE
Settings: Field names cut off in drop down

### ISSUE THREAD

**Issue by mck1777** [ExLibrisGroup/alma-csv-user-load#38]
When entering the field mapping is there a trick to see the whole choice? I had a staff member ask me as she was unable to view the whole line and was confused on which to choose
Note visible to patrons (true/false)
Note pops up in patron services (true/false)
![popup](https://user-images.githubusercontent.com/72558867/124145761-138fc380-da5b-11eb-8965-153cd33acdb8.png)
I showed her the  documentation but was wondering if I failed to see how to extend the side bar on the cloud app.

No enhance being requested, just wondered if I missed something.

Thanks
mck

**Comment by jweisman** [comment]
Hi @mck1777 . I agree it's hard to see the text cut off. Let's leave this issue open as a bug and see if we can make it any better.

**Comment by mck1777** [comment]
Thanks. That would be appreciated.

**Comment by mgobat** [comment]
We will address this by allowing the Alma CSV User Load Cloud App to go full screen.

**Comment by mgobat** [comment]
Available in v1.6.5.
