### ISSUE TITLE
Identifier types

### ISSUE THREAD

**Issue by RAVatwork** [ExLibrisGroup/alma-csv-user-load#41]
Can this be extended to include identifier types other than BARCODE and INST_ID. We would like to use it to create users with Authentication IDs but I am sure others would find the other available choices useful

**Comment by jweisman** [comment]
Hi @RAVatwork - you should be able to use any identifiers (configured)[https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/050Administration/030User_Management/65viewing_user_identifier_types#Configuring_User_Identifier_Types] for your institution. You just need to use the code for the identifier type. 

Let us know if that works for you.

**Comment by jweisman** [comment]
Closing for now- feel free to open if this is still an issue.
