### ISSUE TITLE
Question about errors in load log

### ISSUE THREAD

**Issue by seanpurcell** [ExLibrisGroup/alma-csv-user-load#42]
One of the institutions in our consortia is testing the Alma CSV User loader cloud App, and recently tried a file with about 50 users in it.  The app reported back that 46 were processed and 3 had errors.  Here is a snippet of the resulting log (anonymized).  We're not exactly sure exactly what the error means?  The Primary IDs of the folks with errors do match their primary IDs in Alma, so we're puzzled as to why they aren't getting updated.

>Processed: 9271xxxxxx
Processed: 9275xxxxxx
Processed: 9273xxxxxx
Processed: 9278xxxxxx
Processed: 9271xxxxxx
Processed: 9270xxxxxx
Processed: 2010xxxxxx
Failed: The external id in DB does not fit the given value in xml - external id cannot be updated. (2099xxxx, Baggins, Jane)
Processed: 9271xxxxxx
Processed: 9121xxxxxx
Processed: 9123xxxxxx
Processed: 9120xxxxxx
Processed: 9270xxxxxx
Processed: 9278xxxxxx
Failed: The external id in DB does not fit the given value in xml - external id cannot be updated. (9154xxxx, Strider, Bob)

Thanks!
Sean

**Comment by jweisman** [comment]
Hi @seanpurcell. Thanks for sending the profile export- very helpful!. 

I see that the `external_id` field is indeed in the profile with a default of `SIS`:

```
      {
        "header": "",
        "fieldName": "external_id",
        "default": "SIS"
      },
```

This means that if the field is not specified in the CSV the value `SIS` will be set. If the saved record has a different "owner," the update will fail.

Is the field defined in the profile intentionally?

**Comment by seanpurcell** [comment]
Hi Josh,

Good catch, yes that is set in the profile…  We can pull that out, I don’t recall why we set that to be honest.  We’ll try that.  Can this be left blank or is it required?

Thanks,
Sean

**Comment by jweisman** [comment]
Hi @seanpurcell - I believe that field is mandatory if creating an external user. It's not required if updating external users. So I recommend having a separate profile for updating that doesn't include that field. That way the existing value will be used.

Let us know how that works out for you.
