### ISSUE TITLE
Testing dataset

### ISSUE THREAD

**Issue by VangelisPalaskas** [ExLibrisGroup/alma-csv-user-load#47]
Dear ExLibris community,

During the past weeks I have been trying to testthe Alma CSV User Load app in order to create an Excel/CSV template for external user upload. For that reason, following the [instructions](https://github.com/ExLibrisGroup/alma-csv-user-load/wiki/Alma-CSV-User-Load-Manual), I have built a simple 2-user 'fake' dataset. However, I get a general error when I try to add the users.

<img width="224" alt="Alma_CSV_User_Load_Error_Adding_User" src="https://user-images.githubusercontent.com/89778038/133775682-6f8f7740-70a6-47f6-a20e-09d68cc98c66.png">
Settings:
<img width="417" alt="Alma_CSV_User_Load-Settings" src="https://user-images.githubusercontent.com/89778038/133776967-3e23247c-3f57-4964-aac8-a4675dc556e4.png">

Dataset:
[Test_FodFin_Users.xlsx](https://github.com/ExLibrisGroup/alma-csv-user-load/files/7185225/Test_FodFin_Users.xlsx)
[Test_FodFin_Users_1.csv](https://github.com/ExLibrisGroup/alma-csv-user-load/files/7185227/Test_FodFin_Users_1.csv)

When I try to add/update existing users I get a different different error.

<img width="224" alt="Alma_CSV_User_Load_Error_Existing_User" src="https://user-images.githubusercontent.com/89778038/133779651-ace57b68-39b7-4b3f-9f43-c7e73c7c7ac7.png">

Dataset:
[Original_Users_Anonymised.xlsx](https://github.com/ExLibrisGroup/alma-csv-user-load/files/7185416/Original_Users_Anonymised.xlsx)

Obviously, I am doing something wrong here. Could you please give me any tip on how to tackle this and successfully add/update the users?

**Comment by jweisman** [comment]
Hi @VangelisPalaskas - thanks for your question. It looks like the date format of the expiration date should be 2099-12-31. The error message is not very helpful!

Let us know if that helps.

**Comment by VangelisPalaskas** [comment]
Dear @jweisman, 

Sorry for this 'stupid' question. I just didn't know what was wrong because as you mention the error message was indeed somewhat vague. Turns out that I omitted the dashes in-between (didn't know they were necessary).

It works perfectly now. Many thanks!

Vangelis.

**Comment by jweisman** [comment]
Great to hear! Thanks.
