### ISSUE TITLE
Agregar el campo "Status del registro de usuario"

### ISSUE THREAD

**Issue by MARG7-13** [ExLibrisGroup/alma-csv-user-load#48]
Sería de mucha utilidad para nuestra Biblioteca la integración del campo: Status del registro de usuario (Activo/Inactivo) espero nos puedan apoyar con esta solicitud, ya que de momento todos los usuarios que se crean por default están activos y nosotros requerimos que estén inactivos por default para activarlos cuando acudan a mostrador.

**Comment by jweisman** [comment]
Hi @MARG7-13 - thanks for your request. We have added the status field in the [latest version](https://github.com/ExLibrisGroup/alma-csv-user-load/releases/tag/v1.6.1). Let us know how it goes for you.
