### ISSUE TITLE
Cannot Update Preferred Last Name

### ISSUE THREAD

**Issue by sphwong** [ExLibrisGroup/alma-csv-user-load#50]
I have created the attached file and used the setting as shown in the attached screen capture to update the last name and preferred last name of user records in Alma. However, only last names are modified. Preferred last names remain unchanged. Could you investigate? Thanks.

Regards,
sphwong

[Change Preferred Last Name Test.csv](https://github.com/ExLibrisGroup/alma-csv-user-load/files/7221771/Change.Preferred.Last.Name.Test.csv)
![Screen Cap](https://user-images.githubusercontent.com/91299283/134606684-dcc40fd1-209c-4a11-9757-e4bfd6d32a45.png)

**Comment by jweisman** [comment]
Hi @sphwong - thanks for your question. I've tried out the preferred last name update and it seems to work well for me. Can you please share your profile (see screenshot) and a sample with with better data (i.e. not the same value for Last Name and Preferred Last name?

Thanks!

![Screen Shot 2021-09-29 at 13 44 50 ](https://user-images.githubusercontent.com/80420/135254038-c210b7ad-ea0d-4cdd-9ff4-87ff9cdeb875.png)

**Comment by sphwong** [comment]
Hi Josh @jweisman , 

I have just tried and it works now. Sorry for my late response as I did not receive notification email for your comment.  Many thanks.

Regards,
Steve
