### ISSUE TITLE
Alma-csv-user-load app giving error when processing records

### ISSUE THREAD

**Issue by rodbustos** [ExLibrisGroup/alma-csv-user-load#54]
I am seeing the following error when trying to add new records to our sandbox.

"Failed: 
The web server encountered an unexpected condition that prevented it from fulfilling the request. If the error persists, please use the unique tracking ID when reporting it." 

There is no tracking ID on the page where I see the error

Any idea what the error means?

**Comment by jweisman** [comment]
Hi @rodbustos - thanks for submitting your issue. This error means the record cannot be retrieved for some reason. Does this happen with particular users or all users? Are you able to try to retrieve the user via API using an API key? 

If you would like us to check, please let us know which environment (institution and prod/sandbox) and the problematic user ID.

Thanks.

**Comment by rodbustos** [comment]
Hi @jweisman - The error occurred with a few users.  Not sure about the API question; Sean may know the answer, but he may be out for the holidays as I haven't heard back on my last query to him.

If you could check on your end that would be helpful.  The institution is Augusta University (sandbox) and I will send you the problematic user id via email.

FWIW, I just did another test load with 250 users in the sandbox and that error did not occur.

**Comment by jweisman** [comment]
Hi @rodbustos - has this error happened again?

**Comment by rodbustos** [comment]
Hi @jweisman - the error has not happened again.  Hoping it was an anomaly of some sort.

**Comment by jweisman** [comment]
Thanks- you can reopen if it happens again.
