### ISSUE TITLE
Preferred language field doesn't work

### ISSUE THREAD

**Issue by esthyklein** [ExLibrisGroup/alma-csv-user-load#66]
Hi,
I use your app in Alma and it works great!
I just have an issue with the Preferred language field - default is English but I can't change it! I need Hebrew (that is set on our Alma) - and I can't get it.
Not when I'm setting it as the default value for this filed, and not when filling this in the CSV manually for users.

Are you aware of it? Can you please help?
Thanks!
Esthy

**Comment by mgobat** [comment]
@esthyklein, help me understand the problem a bit better. I've successfully created users with a preferred language of "Hebrew" using the Alma CSV User Load Cloud App by providing "he" in the CSV input file for the "Preferred Language" field. Do you have any more details about the problem? Thanks.

**Comment by esthyklein** [comment]
@mgobat Thank you! That did the trick. I tried "hebrew" and not "he". So of course when I provide "he" it worked well. Thanks you!
(Was there a way I should have known this? couldn't find on documentation)
