### ISSUE TITLE
Update Users adding a record instead

### ISSUE THREAD

**Issue by JonathanLill** [ExLibrisGroup/alma-csv-user-load#69]
I ran this app a few times successfully, but when I've tried to run it recently it doesn't seem to be functioning correctly. It wouldn't surprise me if I'm doing something incorrectly though. I want to update the Job Category field in existing user records. My profile maps two fields in my import csv "Primary identifier" and "Job Category" to "Primary ID" and "Job category" with no default value. When I run it it adds a new user record instead of updating an existing one. The new record is entirely blank except with the correct value in the job category field, and the Alma user unique ID in the primary identifier field. I don't understand why it doesn't seem to be able to match on the primary identifier. It's handling job category correctly in that it will produce an error message if my import value doesn't match a previously defined option.

Am I missing something, or forgetting a step? Or can you offer any guesses why it is not currently working like I expect?

Thanks much,

Jonathan

**Comment by JonathanLill** [comment]
No worries, I understand the need for precise verification. I've attached two screenshots, one of the profile settings and one of the csv test upload.

![userLoad](https://user-images.githubusercontent.com/37414212/167468869-6d39808e-a9e9-4457-ae67-dea3d8f296fc.jpg)


![image](https://user-images.githubusercontent.com/37414212/167468709-aadb0be4-1a6a-457e-b378-adbc51566197.png)

**Comment by mgobat** [comment]
@JonathanLill, thanks...I'll take a look.

**Comment by mgobat** [comment]
@JonathanLill, glad it is working for you, as I have not been able to replicate the problem. Sorry, I can't offer any reasonable explanation; the only difference I see in your cases is the job category in the second csv file does not contain commas...but I tested with your original csv with the commas, and it worked for me. Closing the issue...please create a new one if you encounter further issues.  Thank you.
