### ISSUE TITLE
update/add new identifier without replace the other identifiers

### ISSUE THREAD

**Issue by BarbaraSalfate** [ExLibrisGroup/alma-csv-user-load#70]
Hi,
We tried to add an additional identifier to  users' records but the app replace every identifier  that exist in the records, deleting the other identifiers when add a new one.
How can we update or add only one identifier without update/delete the others identifiers from the user?
Thanks in advance,
Bárbara

**Comment by mgobat** [comment]
@BarbaraSalfate, could please provide the details of your Profile and a sample csv file? Thanks.

**Comment by BarbaraSalfate** [comment]
Hi,
![Imagen1](https://user-images.githubusercontent.com/105246437/168287958-0d075f3d-c2ac-4d42-a3e7-4bca3d2972d9.png)
![Imagen2](https://user-images.githubusercontent.com/105246437/168287990-1c105307-e414-4d9d-9fc2-2650d4c4000d.png)
We want to add only the last identifier.  But the app delete the other identifier if we do not put them in the CSV.
Can you help us, please?

**Comment by BarbaraSalfate** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/105246437/168289764-3ed4e618-0590-489b-ae1e-f3533dbc37a5.png)

**Comment by mgobat** [comment]
@BarbaraSalfate, this is working as designed. From the documentation for the Cloud App:  The update process is "swap all" - any fields provided in the input are replaced in the user record. Lists such as addresses, phone numbers, and email addresses are replaced completely.  https://github.com/ExLibrisGroup/alma-csv-user-load/wiki/Alma-CSV-User-Load-Manual#profile-type

The identifiers are considered a list.

Please open a new issue as an enhancement, if you'd like.

**Comment by BarbaraSalfate** [comment]
Ok, thanks for your fast answer.
Regards,
