### ISSUE TITLE
Data enriching

### ISSUE THREAD

**Issue by Aavalaakso** [ExLibrisGroup/alma-csv-user-load#73]
I need to enrich data for External Users.

Please make update for this: Add more data (not swap all) without deleting earlier.

I need to Add Another Identifier as Internal for External Users without deleting Identifier which is already there. Just ADD more data as Internal segment for External User.

I want to add University ID users who already have Barcode.

Possible?

**Comment by mgobat** [comment]
@Aavalaakso, this sounds like issue #71. Do you agree? Thanks.

**Comment by Aavalaakso** [comment]
Yes it sound like that! So I'm not alone :)

**Comment by Aavalaakso** [comment]
That is also important that it goes in as Internal segment because otherwise my SIS will overrun it during next night.
