### ISSUE TITLE
User role assignment - Internal Roles

### ISSUE THREAD

**Issue by SWITCHconsortium** [ExLibrisGroup/alma-csv-user-load#75]
Our Automatic Role Assignment rules for imported users are based on Job Category with a default rule to create a Patron role in the absence of a job category. When I loaded a set of internal users with no job category, they were assigned all of the enabled roles. If I make all of the enabled roles inactive, only the patron role is created? Is this perhaps some sort of bug?

I tried adding job category as a field and making the default empty.

**Comment by mgobat** [comment]
@SWITCHconsortium, I'm unable to replicate that behavior. Can you confirm that my test matches your scenario?

1. I have 15 roles in my "Automatic Role Assignment Rules" with two Acquisitions roles enabled. One has a "Job Category" parameter of "Acquisitions Manager", the other "Acquisitions Operator".
2. I have a "Default Rule" that only assigns my "Patron Test" profile (my "Profile 1" in the "Output Parameters" section).
3. I have an import file with a single user that DOES NOT contain "Job Category" in the list of fields being imported.
4. After importing the user via the Alma CSV User Load Cloud App, the user has only the "Patron" role associated with the "Patron Test" profile.

Does that somewhat parallel your scenario?

Thanks...

**Comment by mgobat** [comment]
@SWITCHconsortium, glad you are back in business. Be on a lookout for an update adding the "Job Description" field soon (#74).

**Comment by SWITCHconsortium** [comment]
Many thanks!!!
