### ISSUE TITLE
Question: New user accounts are blocked?

### ISSUE THREAD

**Issue by VangelisPalaskas** [ExLibrisGroup/alma-csv-user-load#76]
Hi @mgobat,

Today I have Added new Users with the cloud app but when I try to log in with their credentials in Alma I get the following error: 

User in Alma:
![image](https://user-images.githubusercontent.com/89778038/176672879-3e34e9d0-b733-466d-98bf-576e9838f4c8.png)

Error when logging in:
![image](https://user-images.githubusercontent.com/89778038/176672275-5cbde800-9094-4111-ac2c-007ea7915a55.png)

You can find my CSV file in attachment:
[Internal Users - Dummy.csv](https://github.com/ExLibrisGroup/alma-csv-user-load/files/9019583/Internal.Users.-.Dummy.csv)
[Internal Users - Dummy.xlsx](https://github.com/ExLibrisGroup/alma-csv-user-load/files/9019584/Internal.Users.-.Dummy.xlsx)
 
Are their accounts authorised overnight and hence the error? or am I doing something wrong?

Kind regards,

Vangelis.

**Comment by VangelisPalaskas** [comment]
@mgobat the user already has the role of patron automatically. Even if I assign manually a new role and try to log in it seems that it doesn't work :/

![image](https://user-images.githubusercontent.com/89778038/176836139-e0f32e79-e874-4d20-991d-ed742083a169.png)

**Comment by mgobat** [comment]
@VangelisPalaskas, I have the same behavior with a newly created user with Patron and Instructor roles. I added the "Acquisitions Manager" role, and then I could log in with the newly created user. Can you try adding that same role? Perhaps there's something about "Instructor" and "Patron" that prohibit the user from logging in (I'm not an Alma expert, so surmising at this point...).

**Comment by VangelisPalaskas** [comment]
Thanks for the tip @mgobat. I asked also around within my institution and the Product Manager said that it is normal for this specific case (it has something to do with the institutional sign-in).

Anyway, you can consider the case closed.

Thanks again for the tip!
