### ISSUE TITLE
can't add a new type of user identifier 

### ISSUE THREAD

**Issue by cindywanghui01** [ExLibrisGroup/alma-csv-user-load#77]
86UIC customer reported that using Alma csv user loader can not add user identifier, for example, there is barcode as an identifier type for the user,  He added another identifier type "other"  with the csv user loader, then check the user,  the barcode was overlaid, not adding a new type. 

BR,
Cindy

**Comment by mgobat** [comment]
@cindywanghui01, this is an enhancement request. Please see issue #71. Closing this issue as a duplicate.
