### ISSUE TITLE
Logs show failed: Http failure during parsing for https://<Inst Alma URL> but users were created successfully

### ISSUE THREAD

**Issue by weijunzi01** [ExLibrisGroup/alma-csv-user-load#79]
Hi ,

First of all thank you for this wonderful CloudApp. It is really simple to setup and saves time and effort to create users using CSV file.

The issue I encountered was when i tried to upload over 600 users records via Alma CSV User Load, up till 150th records, it processed successfully and subsequent 151th user record onward it showed "Failed: Http failure during parsing for <INST Alma URL> (abc@1234.com, Mary Lee, )"

But I can see the rest of the failed records created successfully in my Alma instance. 

Is there any limit to the number of records that can be created using this Cloudapp? And what may caused the fail message in the log?

Any advise is greatly appreciated.

Thanks and regards,
Andy

**Comment by Cong81** [comment]
Hi, 

I faced the same trouble as loading new users by CSV file. I tried to load about 700 new users. It successfully loaded 287 new users but there are hundreds of users not loaded with notification error 
![Screenshot 2022-10-19 CSV load user issue](https://user-images.githubusercontent.com/113650920/196604920-9e8d15ea-976f-45ac-a6c6-3dd92218e83a.jpg)
The issue has recently happened as the app limited new records upload into Alma.

Thank you for your consideration.
Cong

**Comment by mgobat** [comment]
@weijunzi01, @Cong81 

In our testing, we've successfully loaded 1000 users using this Cloud App. But there might be something specific to your Profile settings or CSV file itself. First, could you provide the details of the profile you are using? We will look at that first, and if necessary, request a scrubbed version of your CSV file.

Also, using the "Developer Tools" in your web browser, do you see any errors in the "Console"?

Thank you.

**Comment by mgobat** [comment]
@weijunzi01, @Cong81....is this still an issue for either of you? Thanks.
