### ISSUE TITLE
Additional identifiers

### ISSUE THREAD

**Issue by bwychan** [ExLibrisGroup/alma-csv-user-load#81]
I would like the ability to add additional identifiers other than the 2 out of the box ones provided. Possibly at least 2 more. Thanks!

**Comment by mgobat** [comment]
@bwychan, I believe this is already available...at least in the testing I've done. For the additional identifier types, you need to use the "Code" for each identifier type, which may be found in Alma via "Admin > User Management > User Identifier Types".

**Comment by mgobat** [comment]
@bwychan, have you had a chance to try this out? Thanks.

**Comment by bwychan** [comment]
Thanks @mgobat. Since then I have not had to use the manual load app. But will note this for next time!
