### ISSUE TITLE
CSV File : contains new and existing user data : using add/update : Job fails for new records (expects existing ID)

### ISSUE THREAD

**Issue by mbraden001** [ExLibrisGroup/alma-csv-user-load#94]
A CSV file contains user data--some are already in Alma, others are new users to Alma. All have Primary ID (in a column in the CSV)

Configured job using 'add/update'. Existing and new will all be External User Accounts.

Job results: for new users, job fails--expects an existing User Account and match on Primary ID.

So one can only update/enrich External?

Many thanks for your counsel and help.

**Comment by mgobat** [comment]
@mbraden001, I just did a test and successfully created 3 new external users and updated 1 existing external user in the same csv input file. That is the correct use case, right?

My profile had User Type = External and Profile Type = Add/Update.
My input csv file contained the following headers:
First Name;Last Name;External Code;Primary Identifier;User Group;Preferred Language;Expiration Date;Password;Address;Address Type;Email;Email Type;Job Description

What is the header line like in your input csv file?

**Comment by mbraden001** [comment]
Thanks so much.

My csv file was similar, but I'll try the settings (external), alongside add/update. Some of the existing User Accounts are Internal, but I do not know which are internal and which external, so perhaps I'll test a group of existing records, and set configuration for External, add/update, to see whether the App will proceed through these.

Again, thanks.


[Cal State LA]
Mark E. Braden
Library Systems and Metadata Analyst
John F. Kennedy Memorial Library
California State University, Los Angeles
5151 State University Drive
Los Angeles, CA 90032
T 323.343.4828 | ***@***.******@***.***>
Library Staff Profile: http://calstatela.libguides.com/MarkBraden
calstatela.edu<http://www.calstatela.edu/>  |  Pushing Boundaries

**Comment by mgobat** [comment]
@mbraden001, is this still an open issue for you?  Thank you.
