### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by Shenkarlib** [ExLibrisGroup/alma-csv-user-load#98]
I keep getting "Failed: Mandatory field is missing: email"  with all my  uploads
I checked the profile and csv everything seems to be in agreement it is just not recognizing the emails. does it need to be formatted differently?

Shenkarlib

**Comment by mgobat** [comment]
Hi @Shenkarlib, The email address shouldn't require any special formatting.

Please share your import profile so we can investigate. To export your profile:

- select the profile you are using in the "Select a profile" dropdown
- click the "..." button to right of the "Alma CSV User Load" Cloud App name
- click the "gear" icon
- click the "Share" button
- select the "Export current profile" option

Then copy /paste the output file contents or attach the file to the GitHub issue. 

If possible, please share a sanitized version of your input file, too. Sanitized = no sensitive real data. If that's not possible, we will try to create an example cvs file that works with the profile you are using.

Thanks.

**Comment by mgobat** [comment]
Closed due to lack of response.

**Comment by ERL2022** [comment]
I am having the same problem. How can I resolve it?

[Lahey residents fellows.json](https://github.com/user-attachments/files/18606677/Lahey.residents.fellows.json)
