### ISSUE TITLE
adding multiple IDs

### ISSUE THREAD

**Issue by joeriggie** [ExLibrisGroup/alma-csv-user-load#99]
Good morning!

I just used your excellent tool to add some patrons into Alma. It worked as expected, but I have one question. 

I need to have a column for **Identifier Value** and **Identifier Type**.

Is it possible to have _multiple_ **Identifier Value** and **Identifier Type** fields in the loader file to add several identifiers? If so, how?

Thanks again!
- Joe

**Comment by mgobat** [comment]
Hi @joeriggie  

Are the users of type "internal" or "external"? 

Here's an example profile which adds two identifiers to an existing internal user:

![csvProfile](https://github.com/ExLibrisGroup/alma-csv-user-load/assets/45852490/c13b3ec4-7fc4-4562-ac53-1ab3f17183fb)

The content of the csv file would be like:
```
PRIMEID,TYPE1,VALUE1,TYPE2,VALUE2
mgobat,Scopus,mgobatScop,TWITTER,mgobatTwit
```

**Comment by joeriggie** [comment]
Thanks for the reply.

How does it know that value2 is related to type2 and value1 to type1? Is the order important?

**Comment by mgobat** [comment]
@joeriggie, for the first 'Identifier Type' in the input file, it will take the first 'Identifier Value' in the input file, etc. The headers do not matter; it will not pair 'TYPE1' header with 'VALUE1' header. Does that make sense?

**Comment by mgobat** [comment]
Glad to read that, @joeriggie. Closing this issue.
